#!/usr/bin/env bash
# qwen4exp-g1-boot.sh -- gate G1 ("boot + memory fit") box driver for the
# qwen4exp ds4 engine.
#
# The driver runs two legs of the same fixed prompt against the same artifact,
# one after the other, under one GPU lock:
#
#   leg 1  serial   --mtp-draft 1   draft depth 0
#   leg 2  mtp1     --mtp-draft 2   draft depth 1
#
# The MTP head goes to both legs with --mtp-model. The resident set is thus the
# same for both legs, and only the draft depth changes. The depth mapping comes
# from the track fixture, not from this driver:
# serve_configuration.depths.{serial,mtp1}.ds4_mtp_draft_tokens is {1,2}. The
# engine makes a depth from the draft count in
# ds4_qwen4exp_mtp_depth_from_draft_tokens(): depth = draft_tokens - 1.
#
# BOTH LEGS TAKE THE SAME CLI PATH.
# The ds4 CLI has two generation paths (ds4_cli.c, the branch after the
# diagnostic block). A leg with --temp 0 and --mtp-draft 1 satisfies no clause
# of that branch, so it falls to ds4_engine_generate_argmax(), which starts its
# prefill timer BEFORE ds4_session_create() and does no GPU warm-up. A leg with
# --mtp-draft 2 satisfies the draft-tokens clause and goes to
# run_sampled_generation(), which warms the GPU up first and excludes the
# warm-up from the timer. Those two sets of numbers are not comparable.
#
# The driver therefore sets DS4_CLI_FORCE_SESSION=1 on both legs. That is the
# override the CLI provides for this purpose -- its comment says it "exists so
# TP-vs-single-node validation compares like with like" -- and it sends both
# legs through run_sampled_generation(). Both legs then pay the same warm-up,
# exclude it from the same timer, and start the prefill clock at the same point.
# Both stay greedy at --temp 0: the serial leg through the greedy_argmax path,
# the mtp1 leg through ds4_session_sample() at temperature 0.
#
# The driver records, for each leg: the time to the first generated byte, the
# prefill and generation tok/s the engine itself prints, the peak RSS, the GPU
# memory high-water per process at 1 Hz, and the generated stream. It then
# compares the two streams and writes one JSON summary.
#
# MEMORY SAFETY. Nothing loads until all of these hold:
#
#   * each pinned file is present with exactly the byte count the fixture
#     declares (setup.sh owns the sha256 sums; this driver does not re-hash);
#   * the GPU lock is HELD, not only requested;
#   * MemAvailable covers the budget and the headroom. The driver tests this
#     twice: before it waits for the lock, and again with the lock held. The box
#     can fill while the driver waits in the queue.
#
# THE BUDGET. The artifact holds ~103.7 GiB of body and a 2.6 GiB MTP head, but
# the body is not all resident. The per-layer n-gram (PLE) table stays mapped on
# the solid-state disk. The engine puts it in its own family and subtracts it:
#
#   ds4_qwen4exp.inc: plan->ssd_bytes = plan->bytes[DS4_QWEN4EXP_MEM_PLE];
#                     plan->resident_bytes = plan->total_bytes - plan->ssd_bytes;
#
# The driver subtracts the same tensor. It reads the size from the GGUF tensor
# index. It does not guess the size and it does not hold a copy of the number.
# If it counted the table as resident, it would refuse a load that fits. If it
# held a fixed size, it would under-count a different artifact.
#
#   required = body bytes - PLE table bytes    resident weights
#            + MTP head bytes                  resident head
#            + session budget                  KV, state, activations, PLE window
#            + headroom                        10 GiB, the engine's own
#                                              DS4_QWEN4EXP_MEMORY_HEADROOM_BYTES
#
# WATCHDOG. While a leg runs, the driver reads MemAvailable once each second. If
# the value falls below the floor, the driver kills the whole run process group
# and exits non-zero. The engine's own guard acts before the engine allocates.
# This watchdog covers everything after that point.
#
# HALT. The driver puts itself in its own process group and writes its pid and
# its pgid into the run directory. tools/qwen4exp-g1-halt.sh RUNDIR stops the
# driver, both samplers and ds4 from outside.
#
# GATE OVERRIDES. The budget, the headroom and the floor cannot be weakened on a
# real run. A value weaker than the default is refused by name. To test the
# mechanics of the gate itself, pass --mechanics-test. That mode accepts a
# substitute memory source and any budget value, prints a banner, and marks the
# summary. Its results are never a gate result.
#
# EXIT CODES
#   0  both legs ran and the streams agree
#   2  refusal before any load (missing tool, missing file, pin, budget, memory)
#   3  another run holds the GPU lock
#   4  the watchdog killed the run
#   5  a leg exited non-zero
#   6  the serial and mtp1 streams disagree
#   7  a leg generated no tokens (no-output), which is never a pass
set -euo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null && pwd -P)"

# --- own process group ------------------------------------------------------
# The run must be its own process group, so that halt reaches ds4, the watchdog
# and the samplers together, and so that a signal for the run never reaches the
# shell that started it. The driver re-execs itself once under setsid. This
# happens before the arguments are read, so the re-exec carries the caller's
# argv through unchanged. A box without setsid is refused below, because the
# alternative is to write the operator's own process group.
if [ "${QWEN4EXP_G1_SETSID:-0}" != "1" ] && command -v setsid >/dev/null 2>&1; then
  self_pgid="$(ps -o pgid= -p $$ 2>/dev/null | tr -d '[:space:]' || true)"
  if [ "${self_pgid}" != "$$" ]; then
    export QWEN4EXP_G1_SETSID=1
    exec setsid --wait "${BASH_SOURCE[0]}" "$@"
  fi
fi
export QWEN4EXP_G1_SETSID=1

# --- defaults ---------------------------------------------------------------
BUILD_DIR=""
ARTIFACT_DIR=""
RUN_ROOT=""
DRY_RUN=0
MECHANICS_TEST=0
# The golden's prompt prefix. See the note above leg_cmd.
PROMPT_TOKENS=1024
TOKENS=64
CTX=4096
PROMPT_FILE="${REPO_DIR}/correctness_prompts/public_longcopy_gate_english_1024.txt"
FIXTURE="${REPO_DIR}/fixtures/qwen3_8_125b_a6b_track.json"
LOCK_PATH=/tmp/mtplx-gpu-exclusive.lock
LOCK_WAIT=600
MEMINFO=/proc/meminfo

# The floors of the budget. A real run may raise any of these and may not lower
# any of them.
#   headroom  10 GiB, the engine's own DS4_QWEN4EXP_MEMORY_HEADROOM_BYTES. The
#             driver's gate and the engine's gate then agree.
#   session   KV and GDN recurrent state, the indexer tape, the dilated PLE
#             convolution window, and the activations of one forward. The engine
#             sizes this exactly in ds4_qwen4exp_session_plan_compute(n_ctx,
#             n_batch). At context 4096 every term is well under 2 GiB, so 4 GiB
#             is a deliberate over-statement. Raise it for a longer context.
#   floor     the watchdog floor on MemAvailable.
MIN_HEADROOM_GIB=10
MIN_SESSION_GIB=4
MIN_FLOOR_GIB=8
HEADROOM_GIB="${MIN_HEADROOM_GIB}"
SESSION_GIB="${MIN_SESSION_GIB}"
FLOOR_GIB="${MIN_FLOOR_GIB}"

usage() {
  cat <<'EOF'
usage: qwen4exp-g1-boot.sh --build DIR --artifact DIR [options]

  --build DIR          built ds4 tree, which must hold an executable ds4
  --artifact DIR       directory of the pinned GGUF shards and the MTP head
  --run-dir DIR        parent of the timestamped run directory
                       (default: <build>/g1-runs)
  --dry-run            print the exact ds4 command lines and stop. Takes no
                       lock, reads no memory, loads nothing
  --tokens N           generated tokens for each leg (default 64)
  --prompt-tokens N    prompt-token prefix each leg sends (default 1024, the
                       golden's prefix; the prompt file tokenizes to 1054)
  --ctx N              allocated context tokens (default 4096)
  --prompt FILE        prompt file (default: the public correctness prompt)
  --fixture FILE       track fixture with target.files (default: this repo's)
  --session-gib N      session, KV and scratch budget (default and minimum 4)
  --headroom-gib N     refusal headroom (default and minimum 10)
  --floor-gib N        watchdog MemAvailable floor (default and minimum 8)
  --lock PATH          GPU lock (default /tmp/mtplx-gpu-exclusive.lock)
  --lock-wait SEC      seconds to wait for the lock (default 600)
  --mechanics-test     test the mechanics of the gate itself. Removes the
                       minimums above and permits --meminfo. The summary names
                       the mode. Results are not gate results
  --meminfo FILE       substitute memory source. --mechanics-test only
  -h, --help           this text
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --build)          BUILD_DIR="$2"; shift 2 ;;
    --artifact)       ARTIFACT_DIR="$2"; shift 2 ;;
    --run-dir)        RUN_ROOT="$2"; shift 2 ;;
    --dry-run)        DRY_RUN=1; shift ;;
    --mechanics-test) MECHANICS_TEST=1; shift ;;
    --tokens)         TOKENS="$2"; shift 2 ;;
    --prompt-tokens)  PROMPT_TOKENS="$2"; shift 2 ;;
    --ctx)            CTX="$2"; shift 2 ;;
    --prompt)         PROMPT_FILE="$2"; shift 2 ;;
    --fixture)        FIXTURE="$2"; shift 2 ;;
    --session-gib)    SESSION_GIB="$2"; shift 2 ;;
    --headroom-gib)   HEADROOM_GIB="$2"; shift 2 ;;
    --floor-gib)      FLOOR_GIB="$2"; shift 2 ;;
    --lock)           LOCK_PATH="$2"; shift 2 ;;
    --lock-wait)      LOCK_WAIT="$2"; shift 2 ;;
    --meminfo)        MEMINFO="$2"; shift 2 ;;
    -h|--help)        usage; exit 0 ;;
    *) printf 'qwen4exp-g1-boot: unknown argument %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

GIB=1073741824

refuse() { # refuse NAME MESSAGE...
  local name="$1"; shift
  printf 'qwen4exp-g1-boot: REFUSE %s: %s\n' "${name}" "$*" >&2
  exit 2
}

[ -n "${BUILD_DIR}" ]    || refuse missing-argument "--build DIR is required"
[ -n "${ARTIFACT_DIR}" ] || refuse missing-argument "--artifact DIR is required"

is_uint() { case "$1" in ''|*[!0-9]*) return 1 ;; *) return 0 ;; esac; }
for pair in "TOKENS:${TOKENS}" "CTX:${CTX}" "LOCK_WAIT:${LOCK_WAIT}" \
            "SESSION_GIB:${SESSION_GIB}" "HEADROOM_GIB:${HEADROOM_GIB}" "FLOOR_GIB:${FLOOR_GIB}"; do
  is_uint "${pair#*:}" || refuse bad-argument "${pair%%:*} must be a non-negative integer, got '${pair#*:}'"
done

# --- gate overrides ---------------------------------------------------------
# A real run cannot weaken its own gate. Only --mechanics-test lifts the
# minimums, and it says so in every place the run is reported.
if [ "${MECHANICS_TEST}" -eq 1 ]; then
  printf 'qwen4exp-g1-boot: MECHANICS TEST -- the budget minimums are lifted and the memory source may be substituted. This run is not a gate result.\n' >&2
else
  [ "${MEMINFO}" = "/proc/meminfo" ] \
    || refuse gate-override "--meminfo needs --mechanics-test; a real run reads /proc/meminfo"
  [ "${HEADROOM_GIB}" -ge "${MIN_HEADROOM_GIB}" ] \
    || refuse gate-override "--headroom-gib ${HEADROOM_GIB} is below the engine's own ${MIN_HEADROOM_GIB} GiB headroom; a real run may raise it, never lower it"
  [ "${SESSION_GIB}" -ge "${MIN_SESSION_GIB}" ] \
    || refuse gate-override "--session-gib ${SESSION_GIB} is below the ${MIN_SESSION_GIB} GiB session budget; a real run may raise it, never lower it"
  [ "${FLOOR_GIB}" -ge "${MIN_FLOOR_GIB}" ] \
    || refuse gate-override "--floor-gib ${FLOOR_GIB} is below the ${MIN_FLOOR_GIB} GiB watchdog floor; a real run may raise it, never lower it"
fi

# --- tools ------------------------------------------------------------------
# Each of these carries a deliverable or a safety property. A missing one is a
# refusal by name, not a silently absent field in the summary.
need_tool() { # need_tool PATH_OR_NAME WHAT_IT_IS_FOR
  if [ "${1#/}" != "$1" ]; then
    [ -x "$1" ] || refuse missing-tool "$1 is required for $2"
  else
    command -v "$1" >/dev/null 2>&1 || refuse missing-tool "$1 is required for $2"
  fi
}
need_tool python3      "reading the fixture and the GGUF tensor index"
need_tool /usr/bin/time "the peak RSS of each leg"
need_tool sha256sum    "identifying each leg's generated stream"
need_tool nvidia-smi   "the GPU memory high-water of each leg"
need_tool flock        "holding the GPU lock"
need_tool pgrep        "finding the run's processes for the watchdog and for halt"
need_tool stdbuf       "unbuffering the generated bytes, without which the time to first token is a flush boundary"
need_tool setsid       "putting the run in its own process group; without it halt would have to signal the operator's group"

DS4_BIN="${BUILD_DIR%/}/ds4"
[ -x "${DS4_BIN}" ]     || refuse missing-engine "no executable ds4 at ${DS4_BIN}"
[ -r "${PROMPT_FILE}" ] || refuse missing-prompt "cannot read the prompt file ${PROMPT_FILE}"
[ -r "${FIXTURE}" ]     || refuse missing-fixture "cannot read the track fixture ${FIXTURE}"

# --- pins -------------------------------------------------------------------
# setup.sh owns the sha256 verification of these files. The driver asserts that
# each file on disk still has exactly the pinned size, so a truncated or a
# swapped shard cannot reach a load. The shard names and the head name come from
# the fixture, not from a pattern of the driver's own.
PIN_REPORT="$(python3 - "${FIXTURE}" "${ARTIFACT_DIR}" <<'PY'
import json, os, sys
fixture, art = sys.argv[1], sys.argv[2]
files = json.load(open(fixture))["target"]["files"]
shards, head, bad = [], None, []
for f in files:
    p = os.path.join(art, f["path"])
    if not os.path.exists(p):
        bad.append(f"{f['path']}: missing")
        continue
    got = os.path.getsize(p)
    if got != f["bytes"]:
        bad.append(f"{f['path']}: {got} bytes on disk, fixture pins {f['bytes']}")
    if "-of-" in f["path"]:
        shards.append((f["path"], got))
    else:
        head = (f["path"], got)
if bad:
    print("BAD"); print("\n".join(bad)); raise SystemExit(0)
if not shards or head is None:
    print("BAD"); print("the fixture names no sharded body or no MTP head"); raise SystemExit(0)
shards.sort()
print("OK")
print(os.path.join(art, shards[0][0]))
print(os.path.join(art, head[0]))
print(sum(b for _, b in shards))
print(head[1])
PY
)" || refuse fixture-read "cannot read target.files out of ${FIXTURE}"

if [ "$(printf '%s\n' "${PIN_REPORT}" | head -1)" != "OK" ]; then
  refuse pin-mismatch "$(printf '%s\n' "${PIN_REPORT}" | tail -n +2 | tr '\n' ';')"
fi
MODEL_SHARD1="$(printf '%s\n' "${PIN_REPORT}" | sed -n 2p)"
MTP_PATH="$(printf '%s\n' "${PIN_REPORT}" | sed -n 3p)"
BODY_BYTES="$(printf '%s\n' "${PIN_REPORT}" | sed -n 4p)"
HEAD_BYTES="$(printf '%s\n' "${PIN_REPORT}" | sed -n 5p)"

# --- the PLE table, from the GGUF tensor index ------------------------------
# per_layer_token_embd.weight is the n-gram table. The engine puts it in
# DS4_QWEN4EXP_MEM_PLE and subtracts it from the resident total. So does the
# driver. The reader below opens only GGUF headers. The tensor index sits at the
# front of each shard, so no weight byte is read.
#
# The driver holds no copy of the engine's type table. It reads the one type the
# fixture pins for this tensor (target.quantization.ple_table) and refuses when
# the file disagrees with the pin. The block geometry of that type is checked
# against the file: a wrong pair would not divide the tensor evenly.
PLE_BYTES="$(python3 - "${MODEL_SHARD1}" "${FIXTURE}" <<'PY'
import json, os, re, struct, sys

# The pinned quantization of the PLE table, and its GGUF block geometry. This is
# one entry, for the one tensor the driver sizes -- not a copy of the engine's
# gguf_types[]. ds4.c records the same pair with the same derivation: "IQ4_NL is
# 32 values per block in 18 bytes: one f16 scale and 16 packed nibbles."
# This reader is superseded by tools/gguf-tensor-bytes.py when PR #91 lands.
GEOMETRY = {"IQ4_NL": (20, 32, 18)}

def rd(f, n):
    b = f.read(n)
    if len(b) != n: raise SystemExit("gguf: short read")
    return b
def u32(f): return struct.unpack("<I", rd(f, 4))[0]
def u64(f): return struct.unpack("<Q", rd(f, 8))[0]
def st(f):  return rd(f, u64(f)).decode("utf-8", "replace")

def skip_value(f, t):
    if   t in (0, 1, 7):    rd(f, 1)
    elif t in (2, 3):       rd(f, 2)
    elif t in (4, 5, 6):    rd(f, 4)
    elif t in (10, 11, 12): rd(f, 8)
    elif t == 8:            st(f)
    elif t == 9:
        et = u32(f)
        for _ in range(u64(f)): skip_value(f, et)
    else: raise SystemExit(f"gguf: unknown metadata type {t}")

def scan(path, want_id, blk, size):
    with open(path, "rb") as f:
        if rd(f, 4) != b"GGUF": raise SystemExit(f"gguf: {path} is not a GGUF file")
        u32(f)
        n_tensors, n_kv = u64(f), u64(f)
        for _ in range(n_kv):
            st(f); skip_value(f, u32(f))
        for _ in range(n_tensors):
            name = st(f)
            dims = [u64(f) for _ in range(u32(f))]
            ttype = u32(f); u64(f)
            if name != "per_layer_token_embd.weight":
                continue
            if ttype != want_id:
                raise SystemExit(f"gguf: {name} is type {ttype}, the fixture pins type {want_id}")
            n = 1
            for d in dims: n *= d
            if n % blk:
                raise SystemExit(f"gguf: {name} holds {n} values, which is not a whole number of {blk}-value blocks")
            return n // blk * size
    return None

first, fixture = sys.argv[1], sys.argv[2]
pin = json.load(open(fixture))["target"]["quantization"]["ple_table"]
if pin not in GEOMETRY:
    raise SystemExit(f"gguf: the fixture pins the PLE table as {pin}, whose block geometry this driver does not carry")
want_id, blk, size = GEOMETRY[pin]

m = re.match(r"(.*)-(\d{5})-of-(\d{5})\.gguf$", os.path.basename(first))
d = os.path.dirname(first) or "."
paths = [first]
if m:
    stem, total = m.group(1), int(m.group(3))
    paths = [os.path.join(d, f"{stem}-{i:05d}-of-{total:05d}.gguf") for i in range(1, total + 1)]
for p in paths:
    if not os.path.exists(p): raise SystemExit(f"gguf: missing shard {p}")
    b = scan(p, want_id, blk, size)
    if b is not None:
        print(b); raise SystemExit(0)
raise SystemExit("gguf: no per_layer_token_embd.weight in any shard")
PY
)" || refuse ple-unreadable "cannot size per_layer_token_embd.weight from the artifact's GGUF index"

RESIDENT_BYTES=$(( BODY_BYTES - PLE_BYTES ))
SESSION_BYTES=$(( SESSION_GIB * GIB ))
HEADROOM_BYTES=$(( HEADROOM_GIB * GIB ))
FLOOR_KB=$(( FLOOR_GIB * 1024 * 1024 ))
REQUIRED_BYTES=$(( RESIDENT_BYTES + HEAD_BYTES + SESSION_BYTES + HEADROOM_BYTES ))

gib() { awk -v b="$1" 'BEGIN{printf "%.2f", b/1073741824}'; }

# --- the exact commands -----------------------------------------------------
# Every flag comes from the argument loop of ds4_cli.c:
#   -m/--model FILE   shard 00001. model_open() maps the whole -of- family
#   --mtp-model FILE  the external support GGUF. support_model_detect() reads a
#                     qwen4exp nextn head and weights_bind_qwen4exp_mtp() binds
#                     it. --mtp is the wrong flag here: it means an embedded
#                     head and refuses by name for this family
#   --mtp-draft N     the draft-token count. depth = N - 1
#   --prompt-file F   run one long prompt from a file and stop
#   -n/--tokens N     the largest number of generated tokens
#   --temp 0          greedy
#   -c/--ctx N        allocated context tokens
#   --cuda            select the CUDA backend
#   --raw-prompt      send the prompt file's own tokens unchanged. Qwen3.8 Flash
#                     Next has no chat template (no user/assistant/system
#                     markers), and the engine refuses to wrap a prompt without
#                     one. The public correctness prompt is raw text by design.
# DS4_CLI_FORCE_SESSION sends both legs through run_sampled_generation(). See
# the note at the top of this file.
#
# --prompt-tokens IS NOT A TUNING KNOB. The golden is the first 1024 tokens of
# the prompt file, and the file tokenizes to 1054. Without this the CLI decodes
# all 1054 and its first argmax on the full instruction is EOS -- so the leg
# generates nothing and the run compares two empty streams. Both legs send the
# same prefix the golden was authored on, or the comparison is not the golden's.
leg_cmd() { # leg_cmd DRAFT_TOKENS -- prints the argv, one word to a line
  printf '%s\n' \
    env DS4_CLI_FORCE_SESSION=1 \
    "${DS4_BIN}" --cuda --raw-prompt \
    -m "${MODEL_SHARD1}" \
    --mtp-model "${MTP_PATH}" \
    --mtp-draft "$1" \
    --prompt-file "${PROMPT_FILE}" \
    --prompt-tokens "${PROMPT_TOKENS}" \
    -n "${TOKENS}" \
    --temp 0 \
    -c "${CTX}"
}
leg_cmd_line() { leg_cmd "$1" | sed "s/'/'\\\\''/g; s/^/'/; s/\$/'/" | tr '\n' ' '; }

if [ "${DRY_RUN}" -eq 1 ]; then
  cat <<EOF
qwen4exp-g1-boot: dry run -- nothing is locked, nothing is loaded.

  build     ${BUILD_DIR}
  artifact  ${ARTIFACT_DIR}
  prompt    ${PROMPT_FILE}
  fixture   ${FIXTURE}

memory plan
  body (4 shards)      $(gib "${BODY_BYTES}") GiB
  PLE table (SSD)     -$(gib "${PLE_BYTES}") GiB   per_layer_token_embd.weight, mapped, never resident
  resident weights     $(gib "${RESIDENT_BYTES}") GiB
  MTP head             $(gib "${HEAD_BYTES}") GiB
  session/KV/scratch   $(gib "${SESSION_BYTES}") GiB
  headroom             $(gib "${HEADROOM_BYTES}") GiB
  required             $(gib "${REQUIRED_BYTES}") GiB
  watchdog floor       ${FLOOR_GIB} GiB MemAvailable

leg 1 -- serial, draft depth 0
  $(leg_cmd_line 1)

leg 2 -- mtp1, draft depth 1
  $(leg_cmd_line 2)
EOF
  exit 0
fi

# --- run directory ----------------------------------------------------------
RUN_ROOT="${RUN_ROOT:-${BUILD_DIR%/}/g1-runs}"
RUN="${RUN_ROOT%/}/$(date -u +%Y%m%dT%H%M%SZ)-g1"
mkdir -p "${RUN}"
LOG="${RUN}/driver.log"
log() { printf '[%s] %s\n' "$(date -u +%H:%M:%SZ)" "$*" | tee -a "${LOG}"; }

printf '%s\n' "$$" > "${RUN}/run.pid"
ps -o pgid= -p $$ 2>/dev/null | tr -d '[:space:]' > "${RUN}/run.pgid" || true

[ "${MECHANICS_TEST}" -eq 1 ] && log "MECHANICS TEST -- not a gate result"
log "run dir ${RUN}"
log "engine ${DS4_BIN}"
log "artifact ${ARTIFACT_DIR}"
log "pins OK: body $(gib "${BODY_BYTES}") GiB over the fixture's shard list, head $(gib "${HEAD_BYTES}") GiB"
log "memory plan: resident $(gib "${RESIDENT_BYTES}") GiB (body minus the $(gib "${PLE_BYTES}") GiB SSD-resident PLE table) + head $(gib "${HEAD_BYTES}") GiB + session $(gib "${SESSION_BYTES}") GiB + headroom $(gib "${HEADROOM_BYTES}") GiB = $(gib "${REQUIRED_BYTES}") GiB required"

read_avail_kb() {
  local kb
  [ -r "${MEMINFO}" ] || return 1
  kb="$(awk '/^MemAvailable:/ {print $2; exit}' "${MEMINFO}")"
  [ -n "${kb}" ] || return 1
  printf '%s\n' "${kb}"
}

memory_gate() { # memory_gate WHEN
  local kb bytes
  kb="$(read_avail_kb)" \
    || { printf 'qwen4exp-g1-boot: REFUSE memory-unreadable: %s carries no MemAvailable line; refusing to start a %s GiB load blind (%s)\n' "${MEMINFO}" "$(gib "${REQUIRED_BYTES}")" "$1" >&2; exit 2; }
  bytes=$(( kb * 1024 ))
  if [ "${bytes}" -lt "${REQUIRED_BYTES}" ]; then
    printf 'qwen4exp-g1-boot: REFUSE memory-fit: the boot needs %s GiB (resident %s + head %s + session %s + headroom %s) and %s reports %s GiB available (%s). Nothing has been loaded.\n' \
      "$(gib "${REQUIRED_BYTES}")" "$(gib "${RESIDENT_BYTES}")" "$(gib "${HEAD_BYTES}")" \
      "$(gib "${SESSION_BYTES}")" "$(gib "${HEADROOM_BYTES}")" "${MEMINFO}" "$(gib "${bytes}")" "$1" \
      | tee -a "${LOG}" >&2
    exit 2
  fi
  log "memory gate (${1}): $(gib "${bytes}") GiB available, $(gib "${REQUIRED_BYTES}") GiB required -- ok"
}

# Before the lock: refuse at once rather than wait in a queue for a load that
# cannot fit.
memory_gate "before the lock"

# --- GPU lock ---------------------------------------------------------------
exec 9>>"${LOCK_PATH}" || refuse lock-unwritable "cannot open the GPU lock ${LOCK_PATH}"
if ! flock -w "${LOCK_WAIT}" 9; then
  printf 'qwen4exp-g1-boot: REFUSE gpu-lock-busy: %s is held by another run after %ss. Nothing has been loaded.\n' "${LOCK_PATH}" "${LOCK_WAIT}" | tee -a "${LOG}" >&2
  exit 3
fi
log "GPU lock held: ${LOCK_PATH}"

# And again with the lock held: the box may have filled while the driver waited.
memory_gate "with the lock held"

# --- the run process group --------------------------------------------------
# Nothing the driver starts outlives it: not ds4, not a ds4 grandchild, not a
# sampler. The driver leads its own process group, so the group is the run. The
# function kills every member except this shell, which still has a summary to
# write and an exit code to report. The watchdog and the exit trap both use it.
kill_run_group() {
  local pids
  pids="$(pgrep -g "$$" 2>/dev/null | grep -v "^$$\$" || true)"
  if [ -n "${pids}" ]; then
    # Deliberate word splitting: pids is a newline-separated list.
    # shellcheck disable=SC2086
    kill -KILL ${pids} 2>/dev/null || true
  fi
}
trap kill_run_group EXIT

WATCHDOG_TRIPPED=0

# Liveness of a child, for the loop and for the watchdog.
# The state field of /proc/PID/stat is the test, not a signal. A child that has
# exited but is not yet reaped is a zombie, and a signal test on a zombie
# succeeds; the state field reports Z and this returns false. In practice the
# shell reaps a background job soon enough that a signal test usually agrees,
# so this is the stricter of two tests rather than the only correct one. The
# comm field can hold spaces and parentheses, so the state is read after the
# last ")".
leg_alive() {
  local line st
  line="$(cat "/proc/$1/stat" 2>/dev/null)" || return 1
  st="${line##*) }"
  st="${st%% *}"
  [ -n "${st}" ] && [ "${st}" != "Z" ]
}

# Read the engine's timing line out of a stderr capture and print shell
# assignments for the caller to eval. Its own function so it can be tested
# against a synthetic engine without a GPU, an artifact or Linux
# (tools/test-qwen4exp-g1-no-output.sh sources exactly this function).
#
# Prints, always, one assignment per name: prefill, decode, prompt_tok,
# prefill_s, gen_tok, decode_s. A value the line does not carry prints empty.
g1_parse_rates() { # g1_parse_rates STDERR_FILE
  local err="$1" line
  local prefill decode prompt_tok prefill_s gen_tok decode_s
  prefill="$(sed -n 's/.*prefill: \([0-9.]*\) t\/s.*/\1/p' "${err}" 2>/dev/null | tail -1)"
  decode="$(sed -n 's/.*generation: \([0-9.]*\) t\/s.*/\1/p' "${err}" 2>/dev/null | tail -1)"
  # The NEW shape alone carries the counts and the per-phase seconds.
  line="$(grep -E 'generation: [0-9.]+ t/s \([0-9]+ prompt tokens in' "${err}" 2>/dev/null | tail -1 || true)"
  if [ -n "${line}" ]; then
    prompt_tok="$(printf '%s\n' "${line}" | sed -n 's/.*(\([0-9]*\) prompt tokens in .*/\1/p')"
    prefill_s="$(printf '%s\n' "${line}" | sed -n 's/.*prompt tokens in \([0-9.]*\) s,.*/\1/p')"
    gen_tok="$(printf '%s\n' "${line}" | sed -n 's/.*, \([0-9]*\) generated in .*/\1/p')"
    decode_s="$(printf '%s\n' "${line}" | sed -n 's/.*generated in \([0-9.]*\) s).*/\1/p')"
  fi
  printf 'prefill=%s\ndecode=%s\nprompt_tok=%s\nprefill_s=%s\ngen_tok=%s\ndecode_s=%s\n' \
    "${prefill}" "${decode}" "${prompt_tok:-}" "${prefill_s:-}" "${gen_tok:-}" "${decode_s:-}"
}

# THE GENERATED STREAM, which is not the same thing as stdout.
#
# The engine prints its memory plan and then a budget line before the first
# token, and that budget line carries a LIVE reading:
#
#   qwen4exp memory budget: free 119.01 GiB ...   (serial)
#   qwen4exp memory budget: free 118.64 GiB ...   (mtp1)
#
# Hashing stdout whole made the two legs differ on that number alone. The first
# real run on 3751b81 reported stream_mismatch with a stream.diff whose only
# hunk was those two lines, while every generated token was byte-identical --
# a preamble reading a machine's free memory is not a token stream.
#
# So: drop everything through the LAST budget line and compare what follows. The
# raw stdout stays on disk untouched; this writes the stripped stream beside it.
# An engine that prints no budget line at all is compared whole, which is the
# old behaviour and the safe direction -- it can only report a difference that
# is really there.
g1_strip_preamble() { # g1_strip_preamble RAW_STDOUT STREAM_OUT
  local raw="$1" out="$2" last
  last="$(grep -n 'qwen4exp memory budget:' "${raw}" 2>/dev/null | tail -1 | cut -d: -f1)"
  if [ -n "${last}" ]; then
    tail -n +"$(( last + 1 ))" "${raw}" > "${out}"
  else
    cat "${raw}" > "${out}"
  fi
}

# The no-output verdict, as its own function for the same reason. Prints the
# reason, or nothing when the leg produced tokens.
#
# IT MUST BE GIVEN THE STRIPPED STREAM, never raw stdout. The preamble is always
# there, so raw stdout always carries non-whitespace and the text fallback could
# never fire -- exactly the "a banner does not rescue a leg" case it exists for.
g1_no_output_reason() { # g1_no_output_reason GENERATED_TOKENS STDOUT_FILE
  local gen="$1" out="$2"
  if [ -n "${gen}" ] && [ "${gen}" -eq 0 ] 2>/dev/null; then
    printf '0 generated tokens\n'
  elif ! grep -q '[^[:space:]]' "${out}" 2>/dev/null; then
    printf 'no token text on stdout\n'
  fi
}

run_leg() { # run_leg NAME DRAFT_TOKENS
  local name="$1" draft="$2"
  local out="${RUN}/${name}.stdout" err="${RUN}/${name}.stderr"
  local tm="${RUN}/${name}.time" gpu="${RUN}/${name}.gpu.csv" mem="${RUN}/${name}.mem.log"
  local -a cmd=()
  local line
  while IFS= read -r line; do cmd+=("${line}"); done < <(leg_cmd "${draft}")

  : > "${out}"; : > "${err}"; : > "${gpu}"; : > "${mem}"
  log "leg ${name}: $(leg_cmd_line "${draft}")"

  local t0 ttft="" hwm_kb=0 gpu_peak=0 leg_pid
  t0="$(date +%s.%N)"

  # stdbuf keeps the generated bytes unbuffered, so the first-byte stamp is the
  # real time to first token and not a 4 KiB flush boundary.
  /usr/bin/time -v -o "${tm}" stdbuf -o0 "${cmd[@]}" > "${out}" 2> "${err}" &
  leg_pid=$!
  printf '%s\n' "${leg_pid}" > "${RUN}/${name}.pid"

  local tick=0 ds4pid="" kb rss hwm g mine
  while leg_alive "${leg_pid}"; do
    if [ -z "${ttft}" ] && [ -s "${out}" ]; then
      ttft="$(awk -v a="$(date +%s.%N)" -v b="${t0}" 'BEGIN{printf "%.3f", a-b}')"
      log "leg ${name}: first generated byte at ${ttft} s"
    fi
    if [ $(( tick % 20 )) -eq 0 ]; then
      kb="$(read_avail_kb || echo 0)"
      [ -z "${ds4pid}" ] && ds4pid="$(pgrep -P "${leg_pid}" 2>/dev/null | head -1 || true)"
      rss=0; hwm=0
      if [ -n "${ds4pid}" ] && [ -r "/proc/${ds4pid}/status" ]; then
        rss="$(awk '/^VmRSS:/ {print $2; exit}' "/proc/${ds4pid}/status" 2>/dev/null || echo 0)"
        hwm="$(awk '/^VmHWM:/ {print $2; exit}' "/proc/${ds4pid}/status" 2>/dev/null || echo 0)"
      fi
      [ "${hwm:-0}" -gt "${hwm_kb}" ] 2>/dev/null && hwm_kb="${hwm}"
      printf '%s avail_kB=%s rss_kB=%s hwm_kB=%s\n' "$(date -u +%H:%M:%SZ)" "${kb}" "${rss:-0}" "${hwm:-0}" >> "${mem}"

      # The GPU memory of each process, once a second. On a unified-memory box
      # the per-GPU totals read N/A, so the compute-apps view is the one that
      # reports.
      g="$(nvidia-smi --query-compute-apps=pid,used_gpu_memory --format=csv,noheader,nounits 2>/dev/null || true)"
      if [ -n "${g}" ]; then
        printf '%s,%s\n' "$(date -u +%H:%M:%SZ)" "$(printf '%s' "${g}" | tr '\n' ';')" >> "${gpu}"
        mine="$(printf '%s\n' "${g}" | awk -F', *' -v p="${ds4pid:-0}" '$1==p {print $2}' | sort -n | tail -1)"
        [ -n "${mine}" ] && [ "${mine}" -gt "${gpu_peak}" ] 2>/dev/null && gpu_peak="${mine}"
      fi

      # The trip. The liveness re-check matters: the samples above take tens of
      # milliseconds, mostly in the nvidia-smi call, and a leg can end normally
      # inside that window. Without the re-check a reading taken after a clean
      # exit would turn a good run into a kill.
      if [ "${kb}" -gt 0 ] 2>/dev/null && [ "${kb}" -lt "${FLOOR_KB}" ]; then
        if leg_alive "${leg_pid}"; then
          WATCHDOG_TRIPPED=1
          printf 'qwen4exp-g1-boot: WATCHDOG: MemAvailable %s kB is below the %s GiB floor; killing the run process group\n' "${kb}" "${FLOOR_GIB}" | tee -a "${LOG}" >&2
          kill_run_group
          break
        fi
        log "leg ${name}: MemAvailable ${kb} kB is below the floor, but the leg has already exited; not tripping"
      fi
    fi
    tick=$(( tick + 1 ))
    sleep 0.05
  done

  local rc=0
  wait "${leg_pid}" 2>/dev/null || rc=$?
  [ "${WATCHDOG_TRIPPED}" -eq 1 ] && return 4

  # A leg short enough to end inside one poll interval leaves no first-byte
  # stamp. Report the whole leg as an upper bound rather than nothing, and say
  # which it is, so a bound is never read as a measurement.
  local ttft_bounded=false wall
  wall="$(awk -v a="$(date +%s.%N)" -v b="${t0}" 'BEGIN{printf "%.3f", a-b}')"
  if [ -z "${ttft}" ] && [ -s "${out}" ]; then
    ttft="${wall}"
    ttft_bounded=true
    log "leg ${name}: ended inside one poll interval; the time to first byte is an upper bound of ${ttft} s"
  fi

  # The engine's own timing line, in either shape it has had:
  #
  #   OLD  "ds4: prefill: %.2f t/s, generation: %.2f t/s"
  #   NEW  "... generation: %.2f t/s (%d prompt tokens in %.2f s, %d generated in %.2f s)"
  #
  # Both are parsed, because the new one arrives with a vendor-sync and this
  # driver must read a tree from either side of it. The rates come from either;
  # THE COUNTS COME ONLY FROM THE NEW SHAPE and stay null on the old one, which
  # is why the no-output check below does not rest on them alone.
  local prefill decode maxrss gen_tok prompt_tok prefill_s decode_s
  eval "$(g1_parse_rates "${err}")"
  maxrss="$(sed -n 's/.*Maximum resident set size (kbytes): *\([0-9]*\).*/\1/p' "${tm}" 2>/dev/null | tail -1)"
  [ -n "${maxrss}" ] || maxrss="${hwm_kb}"

  # NO OUTPUT IS A NAMED FAILURE, NOT A STREAM MISMATCH AND NEVER A PASS.
  #
  # A leg that generates nothing used to reach the verdict two ways, and both
  # were wrong. With empty stdout the stream comparison never ran and the gate
  # reported stream_mismatch, which points at divergence when the truth is that
  # there is no stream at all. Worse, two legs that both emitted only a banner
  # compared BYTE-IDENTICAL and the gate reported ok -- a zero-output regression
  # reading as a pass, which is exactly how one got through on 278b799.
  #
  # Two independent signals, because neither covers the other: the engine's own
  # count is authoritative but absent on the old line shape, and the stdout text
  # is always there but cannot distinguish a short generation from none.
  # The generated stream, beside the raw capture, and what everything below
  # compares and hashes.
  local stream="${RUN}/${name}.stream"
  g1_strip_preamble "${out}" "${stream}"

  local no_output_reason
  no_output_reason="$(g1_no_output_reason "${gen_tok:-}" "${stream}")"

  cat > "${RUN}/${name}.json" <<EOF
{
  "leg": "${name}",
  "mtp_draft_tokens": ${draft},
  "draft_depth": $(( draft - 1 )),
  "cli_path": "run_sampled_generation (DS4_CLI_FORCE_SESSION=1)",
  "exit_code": ${rc},
  "time_to_first_byte_s": ${ttft:-null},
  "time_to_first_byte_is_upper_bound": ${ttft_bounded},
  "wall_s": ${wall},
  "prefill_tok_s": ${prefill:-null},
  "decode_tok_s": ${decode:-null},
  "prompt_tokens": ${prompt_tok:-null},
  "generated_tokens": ${gen_tok:-null},
  "prefill_s": ${prefill_s:-null},
  "decode_s": ${decode_s:-null},
  "no_output_reason": $( [ -n "${no_output_reason}" ] && printf '"%s"' "${no_output_reason}" || printf null ),
  "peak_rss_kb": ${maxrss:-0},
  "gpu_peak_mib": ${gpu_peak:-0},
  "stdout_sha256": "$(sha256sum "${out}" | cut -d' ' -f1)",
  "stdout_bytes": $(wc -c < "${out}" | tr -d '[:space:]'),
  "stream_sha256": "$(sha256sum "${stream}" | cut -d' ' -f1)",
  "stream_bytes": $(wc -c < "${stream}" | tr -d '[:space:]')
}
EOF
  log "leg ${name}: exit ${rc}, ttft ${ttft:-n/a} s, prefill ${prefill:-n/a} tok/s, decode ${decode:-n/a} tok/s, ${gen_tok:-n/a} generated from ${prompt_tok:-n/a} prompt tokens, peak RSS ${maxrss:-0} kB, GPU peak ${gpu_peak:-0} MiB"
  if [ -n "${no_output_reason}" ]; then
    log "leg ${name}: no-output: ${no_output_reason}"
    return 7
  fi
  return "${rc}"
}

SERIAL_RC=0; run_leg serial 1 || SERIAL_RC=$?
MTP_RC=0
if [ "${SERIAL_RC}" -eq 0 ]; then
  run_leg mtp1 2 || MTP_RC=$?
else
  log "leg serial exited ${SERIAL_RC}; the mtp1 leg does not start"
fi

# --- streams ----------------------------------------------------------------
# The comparison is over the GENERATED STREAMS, not raw stdout: see
# g1_strip_preamble. The raw captures stay on disk either way.
STREAMS_MATCH=null
if [ -s "${RUN}/serial.stream" ] && [ -s "${RUN}/mtp1.stream" ]; then
  if cmp -s "${RUN}/serial.stream" "${RUN}/mtp1.stream"; then
    STREAMS_MATCH=true
    log "streams: serial and mtp1 are byte-identical (generated stream, preamble stripped)"
  else
    STREAMS_MATCH=false
    diff -u "${RUN}/serial.stream" "${RUN}/mtp1.stream" > "${RUN}/stream.diff" 2>&1 || true
    log "streams: serial and mtp1 DIFFER; see ${RUN}/stream.diff"
  fi
fi

STATUS=ok
EXIT=0
if [ "${WATCHDOG_TRIPPED}" -eq 1 ]; then STATUS=watchdog_kill; EXIT=4
elif [ "${SERIAL_RC}" -eq 7 ] || [ "${MTP_RC}" -eq 7 ]; then STATUS=no_output; EXIT=7
elif [ "${SERIAL_RC}" -ne 0 ] || [ "${MTP_RC}" -ne 0 ]; then STATUS=leg_failed; EXIT=5
elif [ "${STREAMS_MATCH}" != "true" ]; then STATUS=stream_mismatch; EXIT=6
fi

python3 - "${RUN}" <<PY > "${RUN}/g1-summary.json"
import json, os, sys
run = sys.argv[1]
def leg(name):
    p = os.path.join(run, name + ".json")
    return json.load(open(p)) if os.path.exists(p) else None
summary = {
    "gate": "G1",
    "status": "${STATUS}",
    "mechanics_test": ${MECHANICS_TEST} == 1,
    "run_dir": run,
    "engine": "${DS4_BIN}",
    "artifact": "${ARTIFACT_DIR}",
    "prompt": "${PROMPT_FILE}",
    "tokens": ${TOKENS},
    "ctx": ${CTX},
    "memory_source": "${MEMINFO}",
    "memory_plan_bytes": {
        "body": ${BODY_BYTES},
        "ple_table_ssd_resident": ${PLE_BYTES},
        "resident_weights": ${RESIDENT_BYTES},
        "mtp_head": ${HEAD_BYTES},
        "session": ${SESSION_BYTES},
        "headroom": ${HEADROOM_BYTES},
        "required": ${REQUIRED_BYTES},
    },
    "watchdog_floor_gib": ${FLOOR_GIB},
    "watchdog_tripped": ${WATCHDOG_TRIPPED} == 1,
    "streams_identical": {"true": True, "false": False, "null": None}["${STREAMS_MATCH}"],
    "legs": {"serial": leg("serial"), "mtp1": leg("mtp1")},
}
json.dump(summary, sys.stdout, indent=2)
sys.stdout.write("\n")
PY

[ "${MECHANICS_TEST}" -eq 1 ] && log "MECHANICS TEST -- not a gate result"
log "status ${STATUS}; summary ${RUN}/g1-summary.json"
exit "${EXIT}"
